### ISSUE TITLE
python quicktest.py

### ISSUE THREAD

**Issue by YUHSINCHENG1230** [amd/ryzen-ai-documentation#230]
after run Manual Installation
I run python quicktest.py have some error 
Is somebody have solution?
cmd error like picture.
![image](https://github.com/amd/ryzen-ai-documentation/assets/160841042/ad7a5b96-4d3e-4545-90d8-ec95f15003e7)

**Comment by poganesh** [comment]
@YUHSINCHENG1230 

These steps worked for me and might be helpful in your case as well. 

1. Download the [ryzen-ai-sw-1.1.zip](https://account.amd.com/en/forms/downloads/ryzen-ai-software-platform-xef.html?filename=ryzen-ai-sw-1.1.zip) Ryzen AI Software installation package and extract it.
2. Start a new conda prompt. In the conda prompt do the following steps:

```
conda create ---name test_env python=3.9
conda activate test_env
cd <your_path>\ryzen-ai-sw-1.1\ryzen-ai-sw-1.1\voe-4.0-win_amd64
pip install voe-0.1.0-cp39-cp39-win_amd64.whl
pip install onnxruntime_vitisai-1.15.1-cp39-cp39-win_amd64.whl
python installer.py
```
3. Runtime Setup: Set the following environment variable in the conda environment created above
`set XLNX_VART_FIRMWARE=<your_path>\ryzen-ai-sw-1.1\ryzen-ai-sw-1.1\voe-4.0-win_amd64\1x4.xclbin`

The `1x4.xclbin` file is located in the `voe-4.0-win_amd64` folder of the Ryzen AI Software installation package.

4. Test the installation:
```
cd ..\quicktest
python quicktest.py
```

Output:
```

[Vitis AI EP] No. of Operators :   CPU     2    IPU   398  99.50%
[Vitis AI EP] No. of Subgraphs :Actually running on IPU     1
2 0 2 4 - 0 2 - 2 2   1 1 : 5 8 : 3 1 . 8 4 8 0 3 0 1   [ W : o n n x r u n t i m e : ,   s e s s i o n _ s t a t e . c c : 1 1 6 9   o n n x r u n t i m e : : V e r i f y E a c h N o d e I s A s s i g n e d T o A n E p ]   S o m e   n o d e s   w e r e   n o t   a s s i g n e d   t o   t h e   p r e f e r r e d   e x e c u t i o n   p r o v i d e r s   w h i c h   m a y   o r   m a y   n o t   h a v e   a n   n e g a t i v e   i m p a c t   o n   p e r f o r m a n c e .   e . g .   O R T   e x p l i c i t l y   a s s i g n s   s h a p e   r e l a t e d   o p s   t o   C P U   t o   i m p r o v e   p e r f .
 2 0 2 4 - 0 2 - 2 2   1 1 : 5 8 : 3 1 . 8 5 4 3 1 2 2   [ W : o n n x r u n t i m e : ,   s e s s i o n _ s t a t e . c c : 1 1 7 1   o n n x r u n t i m e : : V e r i f y E a c h N o d e I s A s s i g n e d T o A n E p ]   R e r u n n i n g   w i t h   v e r b o s e   o u t p u t   o n   a   n o n - m i n i m a l   b u i l d   w i l l   s h o w   n o d e   a s s i g n m e n t s .
 Test Passed
2 0 2 4 - 0 2 - 2 2   1 1 : 5 8 : 3 2 . 7 4 5 0 6 3 9   [ W : o n n x r u n t i m e : D e f a u l t ,   v i t i s a i _ e x e c u t i o n _ p r o v i d e r . c c : 7 4   o n n x r u n t i m e : : V i t i s A I E x e c u t i o n P r o v i d e r : : ~ V i t i s A I E x e c u t i o n P r o v i d e r ]   R e l e a s i n g   t h e   F l e x M L   E P   p o i n t e r   i n   V i t i s   A I   E P
```


Additionally, I recommend checking our [manual installation](https://ryzenai.docs.amd.com/en/latest/manual_installation.html) page for detailed guidance and ensure all instructions in our manual installation guide are accurately followed. Alternatively, consider using our [automatic installer](https://ryzenai.docs.amd.com/en/latest/inst.html#install-the-ryzen-ai-software) for a potentially smoother setup process. 

If the problem still persists, please provide us with the specific steps you followed.

**Comment by YUHSINCHENG1230** [comment]
for step run python installer.py, i have some error like picture.
how can i solve it? 
in C:\Windows\System32\AMD\ is not have those file.
Dirve imformation 
AMD Radeon 760M Graphics
Driver Date: 20241/11
Driver Version: 31.0.24002.92

![image](https://github.com/amd/ryzen-ai-documentation/assets/160841042/773c3806-1ac9-4996-812f-a84c73b09493)

**Comment by uday610** [comment]
Hello @YUHSINCHENG1230 , 
Did you install NPU driver? 

The NPU driver should be shown like below, please check the main installation page: https://ryzenai.docs.amd.com/en/latest/inst.html#prepare-the-system

![image](https://github.com/amd/ryzen-ai-documentation/assets/10237331/d1e844d4-1de5-4fd5-80f5-a896815880a6)

**Comment by YUHSINCHENG1230** [comment]
cmd show i have install the IPU driver ,but in System Devices i can't see there have AMD IPU Device . 
is it the problem?  and how can i solve it?(even i reinstall but even can't see in System Devices)
![image](https://github.com/amd/ryzen-ai-documentation/assets/160841042/4eee00b1-6d19-4cf4-bb02-6ef492b57d70)

**Comment by uday610** [comment]
Please show the full output when you installing the driver.

`.\amd_install_kipudrv.bat`

Also make sure you are opening "Device Manager" and then System Devices -> AMD IPU Device

What is your laptop details?

**Comment by YUHSINCHENG1230** [comment]
@uday610 
the cmd all output is like that image
and i open Device Manager and then System Devices, in there isn't have AMD IPU Device.

**Comment by uday610** [comment]
Your image does not seem complete. 
Your image shows the last line "Do you want to uninstall available and continue with the installation? [Y/n]" 

After that, you must type "Y", what is the output after that? I cannot see you showing me "Y" in your image. I dont even see the first command, I dont see what happens after you type "Y". 

Can you send complete screenshot

Also as asked before what is your laptop/pc details

**Comment by YUHSINCHENG1230** [comment]
and i reinstall the IPU driver output like image
![image](https://github.com/amd/ryzen-ai-documentation/assets/160841042/10ea3d5c-1b47-4e08-b1e8-a18b802e9463)
laptop/pc 
UM760 Pro Venus series

**Comment by YUHSINCHENG1230** [comment]
now the quicktest.py is run successful, i adjust the bios setting, the IPU Control should be enabled.
