### ISSUE TITLE
Feature Request for running 281GB Mistral. APU can be more than 16GB? need 281GB APUs

### ISSUE THREAD

**Issue by ouvaa** [amd/ryzen-ai-documentation#248]
sorry i cant find help for feature requests but motherboards can support > 1TB ram, can you guys make the APU support more than 16GB vram so we can run 281GB mistral model?

i was about to buy another amd ryzen etc but realised how limited the vram always is. hope to have really lots of vram handling capabilities.

16GB vram, amd for AI in 2024?

**Comment by uday610** [comment]
Hi @ouvaa, it seems your feature ask is related to iGPU VRAM support.. 

can you please post in the forum? https://community.amd.com/t5/ai-discussions/bd-p/amd-ai-discussions
