### ISSUE TITLE
Req: support for NPU training

### ISSUE THREAD

**Issue by hawkheimmer** [amd/ryzen-ai-documentation#250]
# Request for NPU Training Support

**Dear Ryzen AI Software Team,**

I am an enthusiastic user of the Ryzen 8040 processor and have been closely following the development of your Ryzen AI software repository with great interest.

My primary interest lies in the potential of training deep neural networks (DNNs) on a Neural Processing Unit (NPU). I believe that the NPU's architecture could significantly expedite the computation of matrices and tensors, which is crucial for deep learning applications. Unfortunately, I noticed that the current version of the software does not support PyTorch for training purposes, compelling me to rely on CUDA instead.

This reliance on CUDA has presented a challenge due to the VRAM limitations, which hinders my ability to train larger and more complex networks. Consequently, I have turned my focus towards the system's RAM capabilities. While CPUs are traditionally not optimized for tensor operations, thus making them less suitable for DNN training, NPUs appear to be a promising alternative.

I am reaching out to inquire if there are any plans to integrate PyTorch support for NPU training in the near future. Such an update would not only enhance the capabilities of your software but also enable many users like myself to push the boundaries of what's possible with Ryzen processors.

Thank you for considering this request. I am looking forward to any updates you might have on this matter.

BTW Intel seemed to have updated their [NPU library](https://intel.github.io/intel-npu-acceleration-library/usage.html) adding support for pytorch training()

**Comment by uday610** [comment]
Hello 
Training using NPU is experimental and has not yet been proven effective. We will continue to monitor its usefulness and make decisions. As of now, there is no concrete plan. 

Thanks
