### ISSUE TITLE
No CONDA found even after adding PATH miniconda3

### ISSUE THREAD

**Issue by Hiro1307** [amd/ryzen-ai-documentation#304]
ryzen-ai-1.2.0-20240726.msi installer keep on saying no conda found even after added the PATH directory and created default env <ryzen-ai-1.2.0>. AMD Ryzen 5 8600g

Error: 'conda' is not recognized as an internal or external command,
operable program or batch file.

**Comment by uday610** [comment]
The Path of Conda should be set to System PATH, not the user PATH 

You can check that in a Powershell


`PS C:\Users\<user_id> [System.Environment]::GetEnvironmentVariable("Path", "Machine")`

**Comment by Hiro1307** [comment]
Hi, thank you very much for replying my message. 

So i check back and added the path to SYSTEM PATH which I did not notice previously and is a new knowledge for me. 

Now it works. Thank you very much for taking your time to reply my concern. Bless you and have a nice day.

**Comment by djh114** [comment]
Always fail to creat conda env:ryzen ai 1.3.0.I have already install miniconda and set The Path of Conda  to System PATH.
